apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydiet
  name: mydiet
  namespace: fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydiet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydiet
    spec:
      containers:
      - image: kube-01.bd.com:5000/fitness/mydiet:0.2
        name: mydiet
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydiet
    release: fitness
  name: mydiet
  namespace: fitness
spec:
  ports:
  - name: http-svc
    nodePort: 30120
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mydiet
  type: NodePort
status:
  loadBalancer: {}
